;;; catppuccin-mocha-theme.el --- Soothing pastel theme for Emacs 🐃

;; Copyright (C) 2023, Nekosis

;; Author: Nekosis
;; Version: 0.1
;; Package-Requires: ((emacs "24.1"))
;; Created with ThemeCreator, https://github.com/mswift42/themecreator.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:
;;; catppuccin-mocha theme created by Nekosis in 2023

;;; Code:

(deftheme catppuccin-mocha)
(let ((class '((class color) (min-colors 89)))
      (fg1 "#cdd6f4")
      (fg2 "#bdc5e0")
      (fg3 "#acb4cd")
      (fg4 "#9ca3b9")
      (fg6 "#d9e0f7")
      (bg1 "#1e1e2e")
      (bg2 "#30303f")
      (bg3 "#42424f")
      (bg4 "#545460")
      (builtin "#89b4fa")
      (keyword "#cba6f7")
      (const   "#fab387")
      (comment "#585B70")
      (func    "#89b4fa")
      (str     "#a6e3a1")
      (type    "#cdd6f4")
      (var     "#cdd6f4")
      (selection "#7f849c")
      (warning   "#f38ba8")
      (warning2  "#fab387")
      (unspec   (when (>= emacs-major-version 29) 'unspecified)))
  (custom-theme-set-faces
   'catppuccin-mocha
   `(default ((,class (:background ,bg1 :foreground ,fg1))))
   `(font-lock-builtin-face ((,class (:foreground ,builtin))))
   `(font-lock-comment-face ((,class (:italic t :foreground ,comment))))
   `(font-lock-negation-char-face ((,class (:foreground ,const))))
   `(font-lock-reference-face ((,class (:foreground ,const))))
   `(font-lock-constant-face ((,class (:foreground ,const))))
   `(font-lock-doc-face ((,class (:foreground ,comment))))
   `(font-lock-function-name-face ((,class (:foreground ,func ))))
   `(font-lock-keyword-face ((,class (:italic t :foreground ,keyword))))
   `(font-lock-string-face ((,class (:foreground ,str))))
   `(font-lock-type-face ((,class (:foreground ,type ))))
   `(font-lock-variable-name-face ((,class (:foreground ,var))))
   `(font-lock-warning-face ((,class (:foreground ,warning :background ,bg2))))
   `(term-color-black ((,class (:foreground ,fg2 :background ,unspec))))
   `(region ((,class (:background ,selection))))
   `(highlight ((,class (:foreground ,fg3 :background ,bg3))))
   `(hl-line ((,class (:background  ,bg2))))
   `(fringe ((,class (:background ,bg1 :foreground ,fg1))))
   `(cursor ((,class (:background ,fg4))))
   `(isearch ((,class (:bold t :foreground ,warning :background ,bg3))))
   `(mode-line ((,class (:background "#181825" :foreground ,fg1))))
   `(mode-line-inactive ((,class (:background "#11111b" :foreground "#6c7086"))))
   `(vertical-border ((,class (:foreground ,fg3))))
   `(minibuffer-prompt ((,class (:bold t :foreground ,keyword))))
   `(default-italic ((,class (:italic t))))
   `(link ((,class (:foreground ,const :underline t))))
   `(org-code ((,class (:foreground ,fg2))))
   `(org-level-1 ((,class (:bold t :foreground "#f38ba8" :height 1.4))))
   `(org-level-2 ((,class (:foreground "#fab387"))))
   `(org-level-3 ((,class (:foreground "#f9e2af"))))
   `(org-level-4 ((,class (:foreground "#a6e3a1"))))
   `(org-document-title ((,class (:bold t :foreground "#f38ba8" :height 1.4))))
   `(org-date ((,class (:underline t :foreground ,var) )))
   `(org-footnote  ((,class (:underline t :foreground ,fg4))))
   `(org-link ((,class (:underline t :foreground ,type ))))
   `(org-special-keyword ((,class (:foreground ,func))))
   `(org-block ((,class (:foreground ,fg3))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-todo ((,class (:box (:line-width 1 :color ,fg3) :foreground ,keyword :bold t))))
   `(org-done ((,class (:box (:line-width 1 :color ,bg3) :bold t :foreground ,bg4))))
   `(org-warning ((,class (:underline t :foreground ,warning))))
   `(org-agenda-structure ((,class (:weight bold :foreground ,fg3 :box (:color ,fg4) :background ,bg3))))
   `(org-agenda-date ((,class (:foreground ,var :height 1.1 ))))
   `(org-agenda-date-weekend ((,class (:weight normal :foreground ,fg4))))
   `(org-agenda-date-today ((,class (:weight bold :foreground ,keyword :height 1.4))))
   `(org-agenda-done ((,class (:foreground ,bg4))))
   `(org-scheduled ((,class (:foreground ,type))))
   `(org-scheduled-today ((,class (:foreground ,func :weight bold :height 1.2))))
   `(org-ellipsis ((,class (:foreground ,builtin))))
   `(org-verbatim ((,class (:foreground ,fg4))))
   `(org-document-info-keyword ((,class (:foreground ,func))))
   `(font-latex-bold-face ((,class (:foreground ,type))))
   `(font-latex-italic-face ((,class (:foreground ,var :italic t))))
   `(font-latex-string-face ((,class (:foreground ,str))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,const))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,var))))
   `(ido-only-match ((,class (:foreground ,warning))))
   `(org-sexp-date ((,class (:foreground ,fg4))))
   `(ido-first-match ((,class (:foreground ,keyword :bold t))))
   `(ivy-current-match ((,class (:foreground ,fg3 :inherit highlight :underline t))))
   `(gnus-header-content ((,class (:foreground ,keyword))))
   `(gnus-header-from ((,class (:foreground ,var))))
   `(gnus-header-name ((,class (:foreground ,type))))
   `(gnus-header-subject ((,class (:foreground ,func :bold t))))
   `(mu4e-view-url-number-face ((,class (:foreground ,type))))
   `(mu4e-cited-1-face ((,class (:foreground ,fg2))))
   `(mu4e-cited-7-face ((,class (:foreground ,fg3))))
   `(mu4e-header-marks-face ((,class (:foreground ,type))))
   `(ffap ((,class (:foreground ,fg4))))
   `(js2-private-function-call ((,class (:foreground ,const))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,str))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,var))))
   `(js2-external-variable ((,class (:foreground ,type  ))))
   `(js2-function-param ((,class (:foreground ,const))))
   `(js2-jsdoc-value ((,class (:foreground ,str))))
   `(js2-private-member ((,class (:foreground ,fg3))))
   `(js3-warning-face ((,class (:underline ,keyword))))
   `(js3-error-face ((,class (:underline ,warning))))
   `(js3-external-variable-face ((,class (:foreground ,var))))
   `(js3-function-param-face ((,class (:foreground ,fg2))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,keyword))))
   `(js3-instance-member-face ((,class (:foreground ,const))))
   `(warning ((,class (:foreground ,warning))))
   `(ac-completion-face ((,class (:underline t :foreground ,keyword))))
   `(info-quoted-name ((,class (:foreground ,builtin))))
   `(info-string ((,class (:foreground ,str))))
   `(icompletep-determined ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-current-face ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-default-face ((,class :foreground ,fg2)))
   `(undo-tree-visualizer-unmodified-face ((,class :foreground ,var)))
   `(undo-tree-visualizer-register-face ((,class :foreground ,type)))
   `(slime-repl-inputed-output-face ((,class (:foreground ,type))))
   `(trailing-whitespace ((,class :foreground ,unspec :background ,warning)))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,fg1)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground "#fab387")))
   `(rainbow-delimiters-depth-3-face ((,class :foreground "#f9e2af")))
   `(rainbow-delimiters-depth-4-face ((,class :foreground "#a6e3a1")))
   `(rainbow-delimiters-depth-5-face ((,class :foreground "#f38ba8")))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,fg1)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground "#fab387")))
   `(rainbow-delimiters-depth-8-face ((,class :foreground "#f9e2af")))
   `(magit-item-highlight ((,class :background ,bg3)))
   `(magit-section-heading        ((,class (:foreground ,keyword :weight bold))))
   `(magit-hunk-heading           ((,class (:background ,bg3))))
   `(magit-section-highlight      ((,class (:background ,bg2))))
   `(magit-hunk-heading-highlight ((,class (:background ,bg3))))
   `(magit-diff-context-highlight ((,class (:background ,bg3 :foreground ,fg3))))
   `(magit-diffstat-added   ((,class (:foreground ,type))))
   `(magit-diffstat-removed ((,class (:foreground ,var))))
   `(magit-process-ok ((,class (:foreground ,func :weight bold))))
   `(magit-process-ng ((,class (:foreground ,warning :weight bold))))
   `(magit-branch ((,class (:foreground ,const :weight bold))))
   `(magit-log-author ((,class (:foreground ,fg3))))
   `(magit-hash ((,class (:foreground ,fg2))))
   `(magit-diff-file-header ((,class (:foreground ,fg2 :background ,bg3))))
   `(lazy-highlight ((,class (:foreground ,fg2 :background ,bg3))))
   `(term ((,class (:foreground ,fg1 :background ,bg1))))
   `(term-color-black ((,class (:background "#585B70" :foreground "#45475A"))))
   `(term-color-red ((,class (:background "#F38BA8" :foreground "#F38BA8"))))
   `(term-color-green ((,class (:background "#A6E3A1" :foreground "#A6E3A1"))))
   `(term-color-yellow ((,class (:background "#F9E2AF" :foreground "#F9E2AF"))))
   `(term-color-blue ((,class (:background "#89B4FA" :foreground "#89B4FA"))))
   `(term-color-magenta ((,class (:background "#F5C2E7" :foreground "#F5C2E7"))))
   `(term-color-cyan ((,class (:background "#94E2D5" :foreground "#94E2D5"))))
   `(term-color-white ((,class (:background "#A6ADC8" :foreground "#A6ADC8"))))
   `(ansi-color-black ((,class (:background "#585B70" :foreground "#585B70"))))
   `(ansi-color-bright-black ((,class (:background "#45475A" :foreground "#45475A"))))
   `(ansi-color-red ((,class (:background "#F38BA8" :foreground "#F38BA8"))))
   `(ansi-color-bright-red ((,class (:background "#F38BA8" :foreground "#F38BA8"))))
   `(ansi-color-green ((,class (:background "#A6E3A1" :foreground "#A6E3A1"))))
   `(ansi-color-bright-green ((,class (:background "#A6E3A1" :foreground "#A6E3A1"))))
   `(ansi-color-yellow ((,class (:background "#F9E2AF" :foreground "#F9E2AF"))))
   `(ansi-color-bright-yellow ((,class (:background "#F9E2AF" :foreground "#F9E2AF"))))
   `(ansi-color-blue ((,class (:background "#89B4FA" :foreground "#89B4FA"))))
   `(ansi-color-bright-blue ((,class (:background "#89B4FA" :foreground "#89B4FA"))))
   `(ansi-color-magenta ((,class (:background "#F5C2E7" :foreground "#F5C2E7"))))
   `(ansi-color-bright-magenta ((,class (:background "#F5C2E7" :foreground "#F5C2E7"))))
   `(ansi-color-cyan ((,class (:background "#94E2D5" :foreground "#94E2D5"))))
   `(ansi-color-bright-cyan ((,class (:background "#94E2D5" :foreground "#94E2D5"))))
   `(ansi-color-white ((,class (:background "#A6ADC8" :foreground "#A6ADC8"))))
   `(ansi-color-bright-white ((,class (:background "#A6ADC8" :foreground "#A6ADC8"))))
   `(line-number ((,class (:inherit default))))))


;; Local Variables:
;; no-byte-compile: t
;; End:

;;; catppuccin-mocha-theme.el ends here
